- name: Copy XRootD server configuration
  template: src={{ item }}.j2 dest=/etc/xrootd/{{ item }} owner=xrootd group=xrootd mode=0644
  with_items:
    - xrootd-standalone.cfg
  notify: Restart XRootD server (standalone)


- name: Copy XRootD server authdb configuration
  template: src={{ item }}.j2 dest=/etc/xrootd/{{ item }} owner=xrootd group=xrootd mode=0644
  with_items:
    - auth_file
  notify: Restart XRootD server (standalone)


- name: Enable and start XRootD server
  service: name={{ item }} enabled=yes state=started
  with_items:
    - xrootd@standalone
