## Baby HTCondor installer (manager)
---
- name: Installs and Configure an HTCondor worknode
  hosts: condor-manager
  roles:
    - common
    - ansible-prereq
    - time
    - ssh-authorized-keys
    - packages
    - condor
  vars_files:
    - /etc/ansible/vars/infrastructure.yml
    - /etc/ansible/vars/mail.yml
    - /etc/ansible/vars/secure.yml

