- hosts: dhcp
  roles:
    - common
    - ansible-prereq
    - time
    - yum-cron
    - ssh-authorized-keys
    - firewall-zones
    - packages
    - dhcp
  vars_files:
    - /etc/ansible/vars/infrastructure.yml
